name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test-pushpull:
    runs-on: ubuntu-latest
    container: swift:5.10.1-jammy
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test
